# Site settings
name: Matthew H. Kutarna
email: matthewkutarna@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Engineering Physics, RF, Electronics, Mechanical, Aerospace, Agile, CAD, PCBs"
skills: "EIT (Engineering Physics) in Vancouver, BC"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/matthewkutarna
#  - title: medium
#    url: https://medium.com/@cgroom
#  - title: twitter
#    url: https://twitter.com/chuck_groom
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 49beb7
  primary-rgb: "73, 190, 183"
  secondary: ff8a5c
  secondary-dark: cc6a43
  section-tout: badfdb

#  primary: 2196F3
#  primary-rgb: "33, 150, 243"
#  secondary: 285172
#  secondary-dark: 29455b
#  section-tout: eaf1f1


# Build settings
markdown: kramdown
permalink: pretty
